name: Lint Code

on:
  push:
    branches:
      - Sprint2_Adam
  pull_request:
    branches:
      - Sprint2_Adam

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, javascript, sql]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install black flake8

      - name: Run black (Auto-format)
        run:           
          black --line-length=100 .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-format code with black" || echo "No changes to commit"
          git push

      - name: Run flake8 (Lint)
        # run: flake8 --max-line-length=100
 
      # JavaScript Linting (ESLint)
      - name: Set up Node.js
        if: matrix.language == 'javascript'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JavaScript Linters
        if: matrix.language == 'javascript'
        run: npm install -g eslint

      - name: Run JavaScript Linter
        if: matrix.language == 'javascript'
        run: eslint.config.js

      # SQL Linting (sqlfluff)
      - name: Install SQL Linter
        if: matrix.language == 'sql'
        run: pip install sqlfluff

      - name: Run SQL Linter
        if: matrix.language == 'sql'
        run: sqlfluff lint --dialect postgres .

